services:
  npm:
    container_name: npm
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./data:/data
      - ./data/letsencrypt:/etc/letsencrypt
    networks:
      - npm_network
  db:
     image: mysql:8.1
     container_name: db
     restart: unless-stopped
     environment:
       MYSQL_ROOT_PASSWORD: 9nx6lD<!Zt2P1xH}A
       MYSQL_DATABASE: InvestTrack
       MYSQL_USER: Victor
       MYSQL_PASSWORD: Victor15*
     ports:
       - "3306:3306"
     volumes:
       - mysql-data:/var/lib/mysql
     networks:
       - npm_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: Victor
      PMA_PASSWORD: Victor15*
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - npm_network
  api:
    container_name: api
    build:
      context: ./InvestTrack-Back
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 5000:5000
    ports:
      - "5000:5000"
    environment:
      TZ: "Europe/Paris"
      PORT: 5000
      DB_NAME: InvestTrack
      DB_USER: Victor
      DB_PASSWORD: Victor15*
      DB_HOST: db
      JWT_SECRET: ma_cle_secrete
      BCRYPT_SALT_ROUNDS: 10
      SMTP_HOST: smtp.mailtrap.io
      SMTP_PORT: 2525
      SMTP_USER: 09765877112471
      SMTP_PASS: 0f40bd0612e0d0
      FROM_EMAIL: no-reply@investtrack.fr
      RAPIDAPI_KEY: d54dfb3a33msh881e344feb01a58p13db32jsnbbdb7b01c1c2
    depends_on:
      - db
    networks:
      - npm_network
  front:
    container_name: front
    build: 
        context: ./InvestTrack
        dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 5173:5173
    ports:
      - "5173:80"
    networks:
      - npm_network
networks:
  npm_network:
    driver: bridge
volumes:
  mysql-data: